sudo: required
language: node
cache:
  directories:
  - node_modules
  - public/videos
env:
  global:
  - secure: YcZTCqPR2u9xi76hGaJtkR2zrF7y6QBXwxXYTQXLFjaxst75udDYQE1SHLuB/83sXyvLQIlApJ8tdJTO4Q/diPiRLXHyxy8s9GKBsEVlhB9fqFMFk3nQ6P9ydtEiEXE0krTuaCyWuBE6ulL9H6AAY9EWKmbWD00i7HInO1whuHsugu8BPk946KYq3uL1OIRx8rpLSc3OMoCQFOkyrwY/LdrMWSeECTxZA+qJHs34mobFlWtjDWipfJ1zzk+l83boLKoJ0+5tB8kc/cR2v4v9C8A2kMfY+R6lBQ+gz3zOMVlIR8/TXcwB0nBu8+VAT7qhr6Xzlns/3BcuC6nEjeQR1+gcPXGLg6RHgsQuT0uEf/E/oJO1f61iWGpZRIdnNvmJQrqj9DhaG0MMbSV2nz37jYotwFYDfP4ulLI+DjKkJa7glXJ8MNhOjJt58HA+2GHfDXgBfZ1IKV9+qCC3GZASvfOiKO+H5zUDrd/CFyOZQx/8ibs7fcLrQHq3GAkRXBQqwIjlLHmyHVddV+eA2AyClDdgcWzOxPnKS1jr8HuXCx2M6v1JrRxqy1b2qBeRKqBWisKo0O67hAqGQ4f2/OkdBu76CLePvrHiIuX8SEUneUdjhX2JZcpyiOFKLAHOPxBgKi9XXCm1eKAPHbekVI4Tzv2EhC5ta1W/t6IBvjucNs4=
  - secure: 4rece59fI1q58BqR9GASz0+JUut/YLuFPH9vUJ9bwnP+yM/GZOYNehbclkUdM+O3bR3NCk3+lagNL1Jn5+3xT29N/SjINliOa7VWBmdkbRtBc1WHlS6XqyNG+yZcbe8VZbk7Ps6gtTpImprO1Cf+x9sbeO1GZNyocObEB/PAclKbm5Y07kR58EL7vkMqn80P/GlNGhL7faMg00OhXAjhIKwdwruWB9rveNEICK7hnSIz4G2kzSEQgNuTjv2dNiIiE7GWZXRdiNCHLNCknhRjf2c+5E3W1R8P+C0QHujLx4wmPwOFjYQfw57Yx+9paaBcIGH4/c6TmHjQCCGUbVuc6mUfuZuk9nJHxPtJR/3a7sFmqE0g0jb/hKcMk87jehddUPbbDzHK9myMV4Wevr3rWV9HhW/ve+5hqYzFHLnh7D3yb+2LZ3m3m5fTmHo2thi1SVvup//AcF5HlkvnzsciwEckr8zU0TOJ6E4DnFTycKCk+l4GzyI7i1YnqFvpr1SebfaluQtdIidgzNRfjAiE1qLZRJ2sr9VnxEJ1oZUhK4mnMu61vvhybRq77wGFJlV+NKQlTCOmLwwK87xhfT5p/BSZy0TBpiseR2kFU+SFO3TqXlazscnCooTUDw5Vor9ovf2hj6DKbUUZeCzjczsXW6yX5I/RPaLhKiYuBTt73/U=
  - secure: 2/+qockrKYzUIrtmTdI3zyGALST0cyJsQMrzqi2HLTkbWuHn9ErEnCkxGHKwUhUPB7EFXDULRLF+8m/MN8mhnkc2K8WrUVu63EBCAXPp7Tw4c1C7POgoMOf+UwWrHx3ofqUWgfEGToEort47zYaC8KpbKWhJXoMCGsijccDFydwNeruLL/Ze7c3suwf/zHfvdODtmXKcm/u21sZiObotE8yoxpPo2dqtM6QkRKps++boPUS81gt0xsGQy0/daB0zKG6L9wh/r9bt3a1i4p2Pwe4kJfLg6eYgq4oeOCwg5ONhZlIOoPXbJXL7xVCWjYvZEMHx7Vo1P4uDhTjHPu/43I8fgRBqMQAaS1HEujuFuGQA4FGIF99i4SgmpLDkSarxjA8ucstIykZ9Dm8b7TAu13XV5vv9dWc8+FvxKjL1U9Xsxf8p8BgcujWMQHHNKjMGp3+eE2s1d8P+B5S7r9V+boSFCTx641ma1O3oSo2cd/Ltu22lKfn5L0SwrW0X/ZB6yLei4Kt3r4kIEH8cUXXhQ8s0aN1xUgyrT04FFgKCtNFzj5PqeLxtBufWrY/OZo6b8I0yFyHVvrNPshgAEP14uEsuDE2DMaczHPXM1WamVVStPVyqMNl9dRbFx4jwftKOW3keH9uiyr50wW5SbFWD9yfmxo0eGUaBXnO9snCmNZY=
services:
- docker
script:
- "./scripts/travis.sh"
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  on:
    branch: master
