version: '2'
services:
  web:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo/test
      - SELENIUM_HOST=selenium
      - NIGHTWATCH_LAUNCH_URL=http://web:3000/
    build: .
    links:
      - redis
      - mongo
      - selenium
    entrypoint: './node_modules/.bin/gulp'
    command: 'server:start'
  redis:
    image: redis
  mongo:
    image: mongo
  selenium:
    image: selenium/standalone-chrome
