version: '2'
services:
  sut:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo/test
      - SAUCE_LABS_USERNAME
      - SAUCE_LABS_ACCESS_KEY
    build: .
    links:
      - redis
      - mongo
    command: 'test'
  redis:
    image: redis
  mongo:
    image: mongo