version: '2'
services:
  base:
    build: ./images/base
    image: laundree/laundree_base
  web:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo/laundree
    build: .
    links:
      - redis
    ports:
      - '80:3000'
  redis:
    image: redis
