mongo:
  url: 'mongodb://localhost/laundree-test'

logging:
  http:
    enabled: false

security:
  password:
    saltRounds: 1

mailer:
  stubTransporter: true
  dryRun: false

defaultUsers:
  test-admin@example.com: admin